// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUKb3xf1Gl4OYANz6AJ6Ltc56bVrY_El0',
    appId: '1:402270938585:web:dca8fcf06b652790e7a5c8',
    messagingSenderId: '402270938585',
    projectId: 'assignment-universalflow',
    authDomain: 'assignment-universalflow.firebaseapp.com',
    storageBucket: 'assignment-universalflow.appspot.com',
    measurementId: 'G-DRSV5PZF4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCClXeJvgkeJB6Qrhk9o--BhVYhJBTIRhk',
    appId: '1:402270938585:android:fa78b522454cfd0ee7a5c8',
    messagingSenderId: '402270938585',
    projectId: 'assignment-universalflow',
    storageBucket: 'assignment-universalflow.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvP9XCoVzkC0U87PTowqidMD1RbqniKnI',
    appId: '1:402270938585:ios:614ef1ccd1ef7a0ce7a5c8',
    messagingSenderId: '402270938585',
    projectId: 'assignment-universalflow',
    storageBucket: 'assignment-universalflow.appspot.com',
    iosClientId: '402270938585-gh5urc3595r5doremf1g0e504nr4p6sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentUniversalflow',
  );
}
